name: Karate API Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:   # allows manual trigger

jobs:
  karate-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build & Run Karate Tests
        run: mvn test -Dtest=TestRunner

      - name: List report files (debug)
        run: ls -R target/karate-reports

      - name: Upload Karate Reports with Timestamp
        uses: actions/upload-artifact@v4
        with:
          name: karate-reports-${{ github.run_id }}
          path: target/karate-reports/
